# Generated by Django 3.2.7 on 2021-12-21 11:43

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.filepath)),
            ],
        ),
    ]
